# docker-compose.yml

version: '3.8'

services:
  db:
    container_name: postgres_pyblog
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Set your PostgreSQL password here
    ports:
      - "5439:5432"

  web:
    container_name: django_pyblog
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
